name: aws-cdk-2.171.1
channels:
  - conda-forge
dependencies:
  - python=3.12
  - nodejs
  - pip
  - pipenv
  - pip:
    - aws-cdk-lib==2.171.1
    - aws-cdk.lambda-layer-kubectl-v31
    - constructs>=10.0.0
    - boto3>=1.28.15
    - botocore>=1.31.15
    - bandit>=1.7.0
    - cdk-nag
    - mkdocstrings
    - mkdocstrings-python
    - mkdocs-material